export const COMMENTS_PLACEHOLDERS = [
  "T'as un palais de Dobermann",
  "J'ai adoré !",
  "Nul à chier",
  "Mieux que Phillipe Etchebest",
  "On dirait un plat de cantine un lundi",
  "Même mon chat ferait mieux",
  "C'est pas avec ça que tu vas percer",
  "J'ai perdu 10 minutes de ma vie",
  "Trop salé, comme ta personnalité",
  "On sent que t'as forcé sur le micro-ondes",
  "J'ai connu des surgelés plus inspirés",
  "C'est pas un plat, c'est une insulte à la gastronomie",
  "On dirait que t'as cuisiné avec les pieds",
  "C'est bien présenté.",
  "Le dressage est propre.",
  "Bonne idée d'association.",
  "C'est original.",
  "Le résultat est soigné.",
  "On voit l'effort.",
  "C'est simple et efficace.",
  "La cuisson a l'air maîtrisée.",
  "Le visuel est sympa.",
];
