export const INGREDIENT_PATTERNS = {
  numericPattern: /^\s*(\d+[.,]?\d*)\s*([a-zÀ-ÿ]+)?\s+(de\s+)?[a-zÀ-ÿ\s]+$/i,
  textualQuantityPattern:
    /^\s*(une|un|des|quelques|plusieurs|demi|demie|quart|tiers)\s+[a-zÀ-ÿ\s]+(de\s+)?[a-zÀ-ÿ\s]+$/i,
  simpleIngredientPattern: /^\s*[a-zÀ-ÿ]{1,15}$/i,
};

export const ACTION_VERBS = [
  "mélanger",
  "ajouter",
  "mettre",
  "verser",
  "incorporer",
  "battre",
  "remuer",
  "pétrir",
  "couper",
  "hacher",
  "émincer",
  "trancher",
  "râper",
  "peler",
  "éplucher",
  "mélangez",
  "ajoutez",
  "mettez",
  "versez",
  "incorporez",
  "battez",
  "remuez",
  "pétrissez",
  "coupez",
  "hachez",
  "émincez",
  "tranchez",
  "râpez",
  "pelez",
  "épluchez",

  "cuire",
  "chauffer",
  "préchauffer",
  "mijoter",
  "bouillir",
  "sauter",
  "frire",
  "griller",
  "rôtir",
  "flamber",
  "cuisez",
  "chauffez",
  "préchauffez",
  "mijotez",
  "faites bouillir",
  "sautez",
  "faites frire",
  "grillez",
  "rôtissez",
  "flambez",

  "laisser",
  "réserver",
  "assaisonner",
  "saler",
  "poivrer",
  "laissez",
  "réservez",
  "assaisonnez",
  "salez",
  "poivrez",
  "garnir",
  "garnissez",
  "servir",
  "servez",
  "dresser",
  "dressez",
  "décorez",
  "décorer",

  "filtrer",
  "filtrez",
  "tamiser",
  "tamisez",
  "fouetter",
  "fouettez",
  "plonger",
  "plongez",
  "retirer",
  "retirez",
  "déposer",
  "déposez",
  "étaler",
  "étalez",
  "former",
  "formez",
  "façonner",
  "façonnez",
  "disposer",
  "disposez",
  "placer",
  "placez",
  "couvrir",
  "couvrez",
];
